import test from "node:test";
import assert from "node:assert/strict";
import { calculateQuote, cents, fingerprint, freezeQuote, normalizeQuoteRequest } from "../lib/cmss-quotes/quote.js";
import { composeEmail, verifyResendWebhook } from "../lib/cmss-quotes/email.js";
import { renderQuotePdf } from "../lib/cmss-quotes/pdf.js";
import { createHmac } from "node:crypto";

const input = { name: "A <script>", company: "CMSS", email: "PAUL@CMSCHOOLSUPPLY.COM", phone: "", notes: "", currency: "USD", expectedSubtotalCents: 360, items: [{ variantId: "32049647157322", quantity: 1, price: 1, title: "fake" }], discountCodes: ["CMSS-EXTRAS10"] };
const response = { data: { draftOrderCalculate: { userErrors: [], calculatedDraftOrder: { presentmentCurrencyCode: "USD", subtotalPriceSet: { presentmentMoney: { amount: "3.6", currencyCode: "USD" } }, discountCodes: ["CMSS-EXTRAS10"], lineItems: [{ name: "Gold Cross", sku: "PCF5335", quantity: 1, variantTitle: "", customAttributes: [], originalUnitPriceSet: { presentmentMoney: { amount: "3.99", currencyCode: "USD" } }, discountedTotalSet: { presentmentMoney: { amount: "3.60", currencyCode: "USD" } } }] } } } };

test("uses Shopify titles and prices", async () => { const quote = await calculateQuote(input, async (_, variables) => { assert.equal(variables.input.lineItems[0].price, undefined); return response; }); assert.equal(quote.items[0].title, "Gold Cross"); assert.equal(quote.subtotalCents, 360); });
test("validates quantities, contact fields, money, and honeypot", () => { assert.equal(cents("3.6"), 360); for (const quantity of [0, -1, 1.5, 1000, "1"]) assert.throws(() => normalizeQuoteRequest({ ...input, items: [{ variantId: "1", quantity }] })); assert.throws(() => normalizeQuoteRequest({ ...input, email: "bad\nBcc:other@example.com" })); assert.throws(() => normalizeQuoteRequest({ ...input, website: "spam" })); });
test("requires cart review when Shopify total changes", async () => { await assert.rejects(calculateQuote({ ...input, expectedSubtotalCents: 399 }, async () => response), (error) => error.code === "PRICE_REVIEW_REQUIRED"); });
test("creates stable request fingerprint", () => { assert.equal(fingerprint(input, "request-key"), fingerprint(input, "request-key")); assert.notEqual(fingerprint(input, "request-key"), fingerprint(input, "other-key")); });
test("renders PDF and escapes customer content", async () => { const quote = freezeQuote(await calculateQuote(input, async () => response), { id: "12345678-abcd-1234-abcd-123456789abc", createdAt: "2026-09-15T00:00:00Z" }); const pdf = await renderQuotePdf(quote); assert(Buffer.from(pdf).subarray(0, 4).equals(Buffer.from("%PDF"))); const message = composeEmail(quote, pdf); assert.deepEqual(message.to, ["paul@cmschoolsupply.com"]); assert(message.html.includes("&lt;script&gt;")); assert(!message.html.includes("<script>")); });
test("verifies Resend webhook signatures and rejects stale signatures", () => { const raw = JSON.stringify({ type: "email.delivered" }), id = "msg_1", now = Math.floor(Date.now() / 1000), secretBytes = Buffer.from("test-secret"), secret = `whsec_${secretBytes.toString("base64")}`, signature = createHmac("sha256", secretBytes).update(`${id}.${now}.${raw}`).digest("base64"); const headers = new Headers({ "svix-id": id, "svix-timestamp": String(now), "svix-signature": `v1,${signature}` }); assert.equal(verifyResendWebhook(raw, headers, secret), true); headers.set("svix-timestamp", String(now - 600)); assert.equal(verifyResendWebhook(raw, headers, secret), false); });
